version: '3'
services:
  db:
    image: postgres
    environment:
      DATABASE_URL: postgres://postgres:qq@localhost:5432/foxes_212
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qq
      POSTGRES_DB: foxes_212
    ports:
      - '5432:5432' # Опционально: это откроет порт 5432 на хост-машине

  app:
    image: btn
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db # Важно: здесь указывается хост базы данных
      - DATABASE_PORT=5432
    ports:
      - '4000:3000'
